# Generated by Django 4.1.13 on 2024-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Module_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Heading', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionsProjectandPolicies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Module_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Heading', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
