# Generated by Django 4.1.13 on 2024-11-27 14:52

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Control',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('employee_code', models.IntegerField(blank=True, null=True)),
                ('Section', models.CharField(max_length=255)),
                ('Page_Name', models.CharField(max_length=255)),
                ('Sub_Page_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Menu_Access', models.BooleanField(default=False)),
                ('View', models.BooleanField(default=True)),
                ('Add', models.BooleanField(default=False)),
                ('Edit', models.BooleanField(default=False)),
                ('Delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Secretary_Access_Control',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Section', models.CharField(max_length=255)),
                ('Page_Name', models.CharField(max_length=255)),
                ('Sub_Page_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Menu_Access', models.BooleanField(default=False)),
                ('View', models.BooleanField(default=True)),
                ('Add', models.BooleanField(default=False)),
                ('Edit', models.BooleanField(default=False)),
                ('Delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Finance_Access_Control',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Section', models.CharField(max_length=255)),
                ('Page_Name', models.CharField(max_length=255)),
                ('Sub_Page_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Menu_Access', models.BooleanField(default=False)),
                ('View', models.BooleanField(default=True)),
                ('Add', models.BooleanField(default=False)),
                ('Edit', models.BooleanField(default=False)),
                ('Delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Human_Resoursce_Access_Control',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Section', models.CharField(max_length=255)),
                ('Page_Name', models.CharField(max_length=255)),
                ('Sub_Page_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Menu_Access', models.BooleanField(default=False)),
                ('View', models.BooleanField(default=True)),
                ('Add', models.BooleanField(default=False)),
                ('Edit', models.BooleanField(default=False)),
                ('Delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_extension', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('location', djongo.models.fields.JSONField()),
                ('employee_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
