# Generated by Django 4.1.13 on 2024-11-27 15:31

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=200, null=True)),
                ('Business_Activity_and_Turnover', djongo.models.fields.JSONField(blank=True, default=list, null=True, unique=True)),
                ('Total_Percent_Turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Activity_Details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_of_Business_Activity', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('company_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('CIN', models.CharField(blank=True, max_length=200, null=True)),
                ('Year_of_Incorporation', models.IntegerField(blank=True, null=True)),
                ('Registered_Office_Address_Line1', models.CharField(blank=True, max_length=500, null=True)),
                ('Registered_Office_Address_Line2', models.CharField(blank=True, max_length=500, null=True)),
                ('Registered_Office_Country', models.CharField(blank=True, max_length=200, null=True)),
                ('Registered_Office_State', models.CharField(blank=True, max_length=200, null=True)),
                ('Registered_Office_City', models.CharField(blank=True, max_length=200, null=True)),
                ('Registered_Office_Pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('Corporate_Office_Address_Line1', models.CharField(blank=True, max_length=500, null=True)),
                ('Corporate_Office_Address_Line2', models.CharField(blank=True, max_length=500, null=True)),
                ('Corporate_Office_Country', models.CharField(blank=True, max_length=200, null=True)),
                ('Corporate_Office_State', models.CharField(blank=True, max_length=200, null=True)),
                ('Corporate_Office_City', models.CharField(blank=True, max_length=200, null=True)),
                ('Corporate_Office_Pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.CharField(blank=True, max_length=200, null=True)),
                ('Website', models.CharField(blank=True, max_length=500, null=True)),
                ('Phone_Ext', models.CharField(blank=True, max_length=10, null=True)),
                ('Phone_Number', models.BigIntegerField(blank=True, null=True)),
                ('Shares_Listed_On', models.CharField(blank=True, max_length=500, null=True)),
                ('CSR_Applicable', models.CharField(blank=True, max_length=100, null=True)),
                ('Company_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Name_of_Assurance_Provider', models.TextField(blank=True, null=True)),
                ('Reporting_Boundary', models.CharField(blank=True, max_length=500, null=True)),
                ('Type_Of_Assurance', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concentration_Of_Purchases',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=200, null=True)),
                ('Purchases_From_Trading_Houses_As_Percent_Of_Total_Purchases', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Number_Of_Trading_Houses_Where_Purchases_Are_Made', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Purchases_From_Top_Ten_Trading_Houses_As_Percent_Of_Total_Purchases_From_Trading_Houses', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concentration_Of_Sales',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=200, null=True)),
                ('Sales_To_Dealers_Divided_BY_Distributors_As_Percent_Of_Total_Sales', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Number_Of_Dealers_Divided_BY_Distributors_To_Whom_Sales_Are_Made', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Sales_To_Top_Ten_Dealers_Divided_BY_Distributors_As_Percent_Of_Total_Sales_To_Dealers_Divided_BY_Distributors', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exports',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=200, null=True)),
                ('Contribution_of_Turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_of_Facility', models.CharField(blank=True, max_length=200, null=True)),
                ('Type_of_Facility', models.CharField(blank=True, max_length=200, null=True)),
                ('Location', models.CharField(blank=True, max_length=500, null=True)),
                ('State', models.CharField(blank=True, max_length=200, null=True)),
                ('Description_of_Operations', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_of_Holding', models.CharField(blank=True, max_length=200, null=True)),
                ('Type_of_Holding', models.CharField(blank=True, max_length=200, null=True)),
                ('Percent_of_Share_Held', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Participates_in_Business_Responsibility', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Markets_Served',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=200, null=True)),
                ('National_No_of_States', models.IntegerField(blank=True, null=True)),
                ('International_No_of_Countries', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Networth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=20, null=True)),
                ('Networth_Apr', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Networth_May', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Networth_Jun', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Networth_Jul', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Networth_Aug', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Networth_Sep', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Networth_Oct', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Networth_Nov', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Networth_Dec', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Networth_Jan', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Networth_Feb', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Networth_Mar', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Total_Networth', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfDaysOfAccountsPayablesModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=200, null=True)),
                ('Days_Of_Accounts_Payables', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offices_and_Plants',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=200, null=True)),
                ('No_of_National_Offices', models.IntegerField(blank=True, null=True)),
                ('No_of_National_Plants', models.IntegerField(blank=True, null=True)),
                ('No_of_International_Offices', models.IntegerField(blank=True, null=True)),
                ('No_of_International_Plants', models.IntegerField(blank=True, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paid_up_Capital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=200, null=True)),
                ('Paid_up_Capital', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Paid_Up_Capital_Unit', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Services',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=200, null=True)),
                ('Products_Services_and_Turnover', djongo.models.fields.JSONField(blank=True, default=list, null=True, unique=True)),
                ('Total_Percent_Turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Services_Details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_of_Product_Service', models.CharField(blank=True, max_length=200, null=True)),
                ('NIC_Code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareOfRPTs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=200, null=True)),
                ('Purchases_With_Related_Parties_As_Percent_Of_Total_Purchases', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Sales_To_Related_Parties_As_Percent_Of_Total_Sales', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Loans_And_Advances_To_Related_Parties_As_Percent_Of_Total_Loans_And_Advances', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Investments_In_Related_Parties_As_Percent_Of_Total_Investments', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Financial_Year', models.CharField(blank=True, max_length=200, null=True)),
                ('Turnover_Apr', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Turnover_May', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Turnover_Jun', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Turnover_Jul', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Turnover_Aug', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Turnover_Sep', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Turnover_Oct', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Turnover_Nov', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Turnover_Dec', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Turnover_Jan', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Turnover_Feb', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Turnover_Mar', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('Total_Turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
        ),
    ]
